"""empty message

Revision ID: 15d1a4a200df
Revises: 658d25e76743
Create Date: 2020-09-20 15:24:58.599076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d1a4a200df'
down_revision = '658d25e76743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('y_n', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bets', 'y_n')
    # ### end Alembic commands ###
