"""empty message

Revision ID: 31592ff17e66
Revises: 
Create Date: 2020-09-03 17:45:18.889452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31592ff17e66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('decider_url', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'decider_url')
    # ### end Alembic commands ###
