"""empty message

Revision ID: e20d8c96f7de
Revises: 15d1a4a200df
Create Date: 2020-11-15 19:09:43.508435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20d8c96f7de'
down_revision = '15d1a4a200df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('decision', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'decision')
    # ### end Alembic commands ###
